# hyprlock — tema morado translucido (rice)
# Colores: bg #140f1a · accent #d946ef · rosa #ec4899 · texto #f0f0ff · dim #8b8bb0

general {
    hide_cursor = false
}

# Fondo: screenshot difuminado con tinte oscuro
background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 7
    noise = 0.012
    contrast = 0.9
    brightness = 0.5
    vibrancy = 0.17
    vibrancy_darkness = 0.2
}

# Reloj grande
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(f0f0ff)
    font_size = 110
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 120
    halign = center
    valign = center
    shadow_passes = 2
    shadow_color = rgb(140f1a)
}

# Fecha
label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %d de %B')"
    color = rgb(c9a0ff)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 30
    halign = center
    valign = center
}

# Usuario (avatar glifo 󰀄)
label {
    monitor =
    text = 󰀄  $USER
    color = rgb(f0f0ff)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, -40
    halign = center
    valign = center
}

# Campo de contraseña
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    rounding = 16
    outer_color = rgb(f0f0ff)
    inner_color = rgba(20, 15, 26, 0.7)
    font_color = rgb(f0f0ff)
    fade_on_empty = false
    placeholder_text = <i><span foreground="##8b8bb0">contraseña...</span></i>
    check_color = rgb(90ff90)
    fail_color = rgb(ec4899)
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    position = 0, -120
    halign = center
    valign = center
}
