background {
    monitor =
    path = screenshot   # toma screenshot y lo difumina
    blur_passes = 3
    blur_size = 7
    brightness = 0.5
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(cba6f7)   # morado pastel
    inner_color = rgb(1e1e2e)   # fondo oscuro
    font_color = rgb(cdd6f4)
    fade_on_empty = true
    placeholder_text = <i>contraseña...</i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(cdd6f4)
    font_size = 64
    font_family = JetBrains Mono
    position = 0, 100
    halign = center
    valign = center
}
