# Monitor AOC (Principal) a 165Hz
monitor = DP-2, 1920x1080@165, 0x0, 1

# Monitor Samsung (Secundario) a 60Hz posicionado a la derecha
monitor = HDMI-A-1, 1920x1080@60, 1920x0, 1

# Asignar workspaces a cada monitor. default:true garantiza que cada pantalla
# siempre tiene al menos 1 workspace. Se pueden mover con SUPER ALT izq/der.
workspace = 1, monitor:DP-2, default:true
workspace = 4, monitor:DP-2
workspace = 2, monitor:HDMI-A-1, default:true
workspace = 3, monitor:HDMI-A-1
workspace = 5, monitor:HDMI-A-1
workspace = 6, monitor:HDMI-A-1
