# Fondo oscuro pero transparente
background #0a0a0a
background_opacity 0.75

# Bordes de la ventana (si los usas)
active_border_color #af5fff
inactive_border_color #444444

# El color del cursor que combine con el morado
cursor #af5fff

# Margen uniforme en los cuatro lados (15px suele ser el "punto dulce")
#window_padding_width 15

# O si quieres un control total (Arriba, Lados, Abajo):
 window_padding_width 10 15 20
font_family JetBrainsMono Nerd Font Mono

# Scroll más suave
scrollback_lines 10000
wheel_scroll_multiplier 5.0

# Abrir URLs con click
open_url_with default

# Copiar al seleccionar
copy_on_select yes
